# Generated by Django 3.1.2 on 2021-08-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstdaset',
            name='super_category_name',
            field=models.CharField(default='default string', max_length=100),
        ),
    ]
