# Generated by Django 3.1.2 on 2021-08-11 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_data', '0002_firstdaset_super_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstdaset',
            name='id',
        ),
        migrations.AlterField(
            model_name='firstdaset',
            name='image_id',
            field=models.CharField(max_length=100, primary_key='True', serialize=False),
        ),
        migrations.CreateModel(
            name='annotations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=100)),
                ('category_name', models.CharField(max_length=100)),
                ('super_category_name', models.CharField(default='default string', max_length=100)),
                ('imageObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='image_data.firstdaset')),
            ],
        ),
    ]
