# Generated by Django 3.1.2 on 2021-08-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_data', '0003_auto_20210811_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotations',
            name='bounding_box',
            field=models.CharField(default='default string', max_length=200),
        ),
        migrations.AddField(
            model_name='annotations',
            name='segmentaions',
            field=models.CharField(default='default string', max_length=400),
        ),
    ]
